Refactor to remove the nxensite/nxdissite scripts
sous-chefs/nginx pull request #565
Opened 2020-11-07 22:15 UTC by bmhughes

# Description

- Refactor cookbook to remove nxensite/nxdissite
- Remove all configuration resources from nginx_install.
- Move all general configuration to nginx_config.
- Refactor nginx_site to remove use of scripts.
- Create nginx_service resource to manage nginx service.
- Remove passenger install option.

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2020-11-07 22:15 UTC, kitchen-porter commented
<!--
  0 Errors
  2 Warnings: This is a big Pull Request.
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a Table Flip.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-09 00:56 UTC, ramereth requested changes
Can you please provide a little context for why these big changes are needed?

2020-11-09 00:56 UTC, ramereth commented on .github/workflows/ci.yml
> +          - 'fedora-32'
This way you don't need to change it on new releases.
```suggestion
          - 'fedora-latest'
```

2020-11-09 00:56 UTC, ramereth commented on CHANGELOG.md
> +## 11.0.0 (2020-11-07)
Let's not do a release as a part of the PR. We'll do that separately.
```suggestion
## Unreleased (2020-11-07)
```

2020-11-09 00:56 UTC, ramereth commented on documentation/nginx_config.md
> +| Name                   | Type          | Default                          | Description                                                         | Allowed Values      |
Is there any reason why we need the `Allowed Values` column if we're not using it?

2020-11-09 00:56 UTC, ramereth commented on documentation/nginx_service.md
> +| Name                   | Type          | Default                          | Description                                                         | Allowed Values      |
Is there any reason why we need the `Allowed Values` column if we're not using it?

2020-11-09 00:56 UTC, ramereth commented on documentation/nginx_site.md
> +| Name                   | Type          | Default                          | Description                                                         | Allowed Values      |
Is there any reason why we need the `Allowed Values` column if we're not using it?

2020-11-09 00:56 UTC, ramereth commented on kitchen.dokken.yml
> +  - name: fedora-32
I recommend you use the following so we don't have to keep updating it on every release.
```suggestion
  - name: fedora-latest
```

2020-11-09 00:56 UTC, ramereth commented on kitchen.yml
> +  - name: fedora-32
```suggestion
  - name: fedora-latest
```

2020-11-09 00:56 UTC, ramereth commented on metadata.rb
> +version          '11.0.0'
Please don't bump cookbooks in PRs.

2020-11-09 00:56 UTC, ramereth commented on resources/install.rb
> -      end
Why is this being removed?

2020-11-09 10:11 UTC, bmhughes commented
> 
> 
> Can you please provide a little context for why these big changes are needed?

I can try.

1. The version 10 cookbook is far less useful/flexible than version 9 was, I get the desire to remove all the recipes and attributes but it removed a **lot** of functionality as well. Especially for anything outside of a normal nginx http site, this doesn't put that back but goes further towards letting the implementing user do it themselves.

2. I'm failing to see anything but restrictions/added complexity with the en/dis scripts. As a site resource is only really a wrapped template resource, why not pass that flexibility through, right now an implementer is stuck to using that paradigm whether they wanted it or not. Afaik it was only ever an Ubuntu thing anyway.

3. There seems to be a general lack of structure, why does the install resource do a bucketful of configuration? Then do it again with the config resource.

4. The hard coded notifies in various resources, would it not be better to allow the wrapper to perform this so the implementing user can use their own process flow?

2020-11-23 23:21 UTC, ramereth commented
@bmhughes can you please rebase and resolve the conflicts? Also fix the metadata validator issue.

2020-11-24 22:05 UTC, ramereth reviewed
I'm on my phone but I wanted to finish part of my review on here. I noticed that this code is not idempotent similar to how the dhcp cookbook is. I'd really to be able to fix that properly somehow. I'll try and take a closer look when I'm back on a laptop.

2020-11-24 22:14 UTC, bmhughes commented
Hmm, thought I'd done the `fedora-latest` change already, not sure how that got missed. Done.

The service ruby_block is a chicken-and-the-egg problem, I can't really see a way to work around it and keep 100% **reliable** service (re)starts with a config test without being able to get service state beforehand on multiple platforms. Otherwise it's back to the notifications stuff that dhcpd used before which has it's own problems. Have a play around and see what you think, I ended up wondering if there was a way to get to the chef service providers to check via those and skip the ruby_block or use converge_by if you can get state..

2020-11-25 11:22 UTC, bmhughes commented
@ramereth I've been doing some more testing and removing the logic from the `ruby_block` still works the same which I didn't expect. I'd have expected it to run into a compile/converge problem and be testing the old configuration during compile, but it doesn't. So I can remove the ruby_block to but I still find that strange.

2020-11-27 18:44 UTC, Xorima commented
@ramereth can you re-review this when you get time please? Be great to get this in

2020-11-27 18:47 UTC, bmhughes commented
> 
> 
> @ramereth can you re-review this when you get time please? Be great to get this in

I'm happily running with this now, but I'm also mindful of the religious war it seemed to spark at the time as well. That said the way there was configuration and service management happening in the install resource it wasn't exactly great as it was either.

On the whole I'm getting vibes of "always done it like that" so I'm happy to move forward with it 🤷🏻‍♂️.

2020-12-01 20:19 UTC, ramereth approved these changes

2020-12-02 06:26 UTC, merged

2020-12-02 06:26 UTC, kitchen-porter commented
Released as: [11.0.0](https://github.com/sous-chefs/nginx/releases/tag/11.0.0)